<Class>
    <Id>74</Id>
    <Package>org.codehaus.groovy.control.messages</Package>
    <ClassName>ExceptionMessage</ClassName>
    <SuperClass>Message</SuperClass>
    <SuperInterfaceList>
        <SuperInterface></SuperInterface>
    </SuperInterfaceList>
    <ClassComment>ExceptionMessage  /** 
 * A class for error messages produced by the parser system.
 * @author &lt;a href="mailto:cpoirier@dreaming.org"&gt;Chris Poirier&lt;/a&gt;
 * @version $Id$
 */
</ClassComment>
    <FieldList>
        <Field>
            <FieldName>verbose</FieldName>
            <FieldType>boolean</FieldType>
        </Field>
        <Field>
            <FieldName>cause</FieldName>
            <FieldType>Exception</FieldType>
        </Field>
        <Field>
            <FieldName>owner</FieldName>
            <FieldType>ProcessingUnit</FieldType>
        </Field>
    </FieldList>
    <MethodList>
        <Method>
            <MethodName>ExceptionMessage</MethodName>
            <MethodComment></MethodComment>
            <ReturnType></ReturnType>
            <ParameterList>
                <Parameter>
                    <ParamName>cause</ParamName>
                    <FieldType>Exception</FieldType>
                </Parameter>
                <Parameter>
                    <ParamName>v</ParamName>
                    <FieldType>boolean</FieldType>
                </Parameter>
                <Parameter>
                    <ParamName>owner</ParamName>
                    <FieldType>ProcessingUnit</FieldType>
                </Parameter>
            </ParameterList>
            <InnerVarList>
                <InnerVar></InnerVar>
            </InnerVarList>
            <InnerMethodInvokeList>
                <InnerMethodInvoke></InnerMethodInvoke>
            </InnerMethodInvokeList>
            <ThrowExceptionList>
                <ExceptionType></ExceptionType>
            </ThrowExceptionList>
        </Method>
        <Method>
            <MethodName>getCause</MethodName>
            <MethodComment>/** 
 * Returns the underlying Exception.
 */
</MethodComment>
            <ReturnType>Exception</ReturnType>
            <ParameterList/>
            <InnerVarList>
                <InnerVar></InnerVar>
            </InnerVarList>
            <InnerMethodInvokeList>
                <InnerMethodInvoke></InnerMethodInvoke>
            </InnerMethodInvokeList>
            <ThrowExceptionList>
                <ExceptionType></ExceptionType>
            </ThrowExceptionList>
        </Method>
        <Method>
            <MethodName>write</MethodName>
            <MethodComment>/** 
 * Writes out a nicely formatted summary of the exception. 
 */
</MethodComment>
            <ReturnType>void</ReturnType>
            <ParameterList>
                <Parameter>
                    <ParamName>output</ParamName>
                    <FieldType>PrintWriter</FieldType>
                </Parameter>
                <Parameter>
                    <ParamName>janitor</ParamName>
                    <FieldType>Janitor</FieldType>
                </Parameter>
            </ParameterList>
            <InnerVarList>
                <InnerVar>String [description="General error during " + owner.getPhaseDescription() + ": "]</InnerVar>
                <InnerVar>String [message=cause.getMessage()]</InnerVar>
            </InnerVarList>
            <InnerMethodInvokeList>
                <InnerMethodInvoke>output;println;[]</InnerMethodInvoke>
                <InnerMethodInvoke>cause;printStackTrace;[output]</InnerMethodInvoke>
            </InnerMethodInvokeList>
            <ThrowExceptionList>
                <ExceptionType></ExceptionType>
            </ThrowExceptionList>
        </Method>
    </MethodList>
</Class>