<Class>
    <Id>2161</Id>
    <Package>org.apache.derbyTesting.functionTests.tests.store</Package>
    <ClassName>backupRestore1</ClassName>
    <SuperClass></SuperClass>
    <SuperInterfaceList>
        <SuperInterface></SuperInterface>
    </SuperInterfaceList>
    <ClassComment>backupRestore1  /** 
 * Test of backup restore through java program JDBC calls. Enhanced the test from bug5229 repro.
 */
</ClassComment>
    <FieldList>
        <Field>
            <FieldName>blob1</FieldName>
            <FieldType>byte[]</FieldType>
        </Field>
        <Field>
            <FieldName>blob2</FieldName>
            <FieldType>byte[]</FieldType>
        </Field>
        <Field>
            <FieldName>blob3</FieldName>
            <FieldType>byte[]</FieldType>
        </Field>
        <Field>
            <FieldName>blob4</FieldName>
            <FieldType>byte[]</FieldType>
        </Field>
        <Field>
            <FieldName>clob1</FieldName>
            <FieldType>byte[]</FieldType>
        </Field>
        <Field>
            <FieldName>clob2</FieldName>
            <FieldType>byte[]</FieldType>
        </Field>
        <Field>
            <FieldName>clob3</FieldName>
            <FieldType>byte[]</FieldType>
        </Field>
        <Field>
            <FieldName>clob4</FieldName>
            <FieldType>byte[]</FieldType>
        </Field>
    </FieldList>
    <MethodList>
        <Method>
            <MethodName>main</MethodName>
            <MethodComment></MethodComment>
            <ReturnType>void</ReturnType>
            <ParameterList>
                <Parameter>
                    <ParamName>args</ParamName>
                    <ParamType>String</ParamType>
                </Parameter>
            </ParameterList>
            <InnerVarList>
                <InnerVar>RandomAccessFile [rfs=null]</InnerVar>
                <InnerVar>boolean [alreadyShutdown=false]</InnerVar>
            </InnerVarList>
            <InnerMethodInvokeList>
                <InnerMethodInvoke>System.out;println;["Test backupRestore starting"]</InnerMethodInvoke>
                <InnerMethodInvoke>System.out;println;["testing rollforward recovery"]</InnerMethodInvoke>
                <InnerMethodInvoke>System.out;println;["Test backupRestore1 finished"]</InnerMethodInvoke>
            </InnerMethodInvokeList>
            <ThrowExceptionList>
                <ExceptionType></ExceptionType>
            </ThrowExceptionList>
        </Method>
        <Method>
            <MethodName>dumpSQLExceptions</MethodName>
            <MethodComment></MethodComment>
            <ReturnType>void</ReturnType>
            <ParameterList>
                <Parameter>
                    <ParamName>se</ParamName>
                    <ParamType>SQLException</ParamType>
                </Parameter>
            </ParameterList>
            <InnerVarList>
                <InnerVar>SQLException [lastSe=se]</InnerVar>
            </InnerVarList>
            <InnerMethodInvokeList>
                <InnerMethodInvoke>System.out;println;["FAIL -- unexpected exception: " + se.toString()]</InnerMethodInvoke>
                <InnerMethodInvoke>System.out;println;[""]</InnerMethodInvoke>
                <InnerMethodInvoke>lastSe;printStackTrace;[System.out]</InnerMethodInvoke>
            </InnerMethodInvokeList>
            <ThrowExceptionList>
                <ExceptionType></ExceptionType>
            </ThrowExceptionList>
        </Method>
    </MethodList>
</Class>