Currently, AssertFailure implements its own chaining of exceptions. It should use the chaining mechanism provided by the JDK.
